development:
  adapter: postgresql
  encoding: unicode
  database: development_psql
  pool: 5
  username: mikey
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: test_psql
  pool: 5
  username: mikey
  password:
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: test_psql
  pool: 5
  username: mikey
  password:
  timeout: 5000
